project:
  title: "MetabolicAnalytics-ShinyLiveApps.github.io"
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js
  - Test_App.html  # Fügen Sie Ihre HTML-App als Ressource hinzu
  
execute:
  engine: knitr

website:
  title: "ShinyApps"
  page-navigation: true
  page-footer:
    right: "[Quarto](https://quarto.org/)"
    left: "Johannes Will, 2025"
      
  sidebar:
    logo: "images/Logo.png"
    pinned: false
    align: center
    style: "docked"
    search: true
    collapse-level: 3 #Ab welchem Level die Unterpunkt nicht mehr angezeigt werden. Bei 2 wird bspw. bei Energieumsatz die Unterpunkte eingeklappt
    contents:
       - Mader_Modell.qmd
       - href: Test_App.html  # Hier Ihre App im Menü hinzufügen
         text: "EPOC-Modell"

      
lang: de
number-sections: true
bibliography: references.bib
csl: apa.csl
format:
  html: 
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 1.5rem
      
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    css: styles.css
    toc: true
    toc-expand: 3
    toc-title: Inhalt auf dieser Seite
    toc-location: right 

    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    
    lightbox: true
    